# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: clouda-commerce-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: clouda-commerce
  name: api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/api: api
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/api: api
    spec:
      containers:
      - image: 210226302225.dkr.ecr.us-east-1.amazonaws.com/saleor-api:0.0.1
        imagePullPolicy: Always
        name: clouda-commerce-api
        env:
        - name: ALLOWED_HOSTS
          value: "k8s-cloudaco-ingressc-a46e621556-1979193842.us-east-1.elb.amazonaws.com"
        - name: DATABASE_URL
          value: "postgres://saleor:saleor@db/saleor"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  namespace: clouda-commerce
  name: service-clouda-commerce-api
spec:
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
  selector:
    app.kubernetes.io/api: api
