# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: clouda-commerce-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: clouda-commerce
  name: db
spec:
  selector:
    matchLabels:
      app.kubernetes.io/db: db
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/db: db
    spec:
      containers:
      - image: library/postgres:13-alpine
        imagePullPolicy: Always
        name: db
        env:
        - name: POSTGRES_USER
          value: "saleor"
        - name: POSTGRES_PASSWORD
          value: "saleor"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: saleor-db
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: saleor-db
        persistentVolumeClaim:
          claimName: efs-claim
---
apiVersion: v1
kind: Service
metadata:
  namespace: clouda-commerce
  name: db
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  type: ClusterIP
  selector:
    app.kubernetes.io/db: db

